Resources:
  ProcessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/${self:provider.stage}-${self:service}
      RetentionInDays: ${self:custom.retentionPeriod}
      
  